### ISSUE TITLE
Appler.exe doesn't actually seem to work on 8088-class CPUs

### ISSUE THREAD

**Issue by mikechambers84** [zajo/appler#3]
Granted, I haven't tried it on real hardware, but in both 86Box (in IBM XT mode) and in XTulator (which emulates an 80186), it doesn't work right. Based on some of the console output in XTulator, execution seems to be jumping off into nowhere. This is using the bin/appler.exe executable. I haven't tried recompiling from source.

It doesn't work in 86Box in 286 mode, either. It finally works when I move up to 386.

![appler](https://user-images.githubusercontent.com/904313/224592486-524f694b-c7d6-4e88-8d38-6d46e823b8b2.png)

![appler2](https://user-images.githubusercontent.com/904313/224592493-dbe0472c-1ee7-4906-a259-07b37afcc86f.png)

**Comment by zajo** [comment]
That's correct, this is why: https://github.com/zajo/appler/blob/develop/src/GLOBALS.INC#L265.

The `AddTiming` macro was added at some point to keep track of the elapsed 6502 cycles in the high 16 bits of `eax`. When the program accesses I/O memory, e.g. `$C030`, Appler waits the accumulated amount of microseconds in an attempt to run at more or less correct speed.

If you really need it to work on a 8088, I believe this is the only thing that needs to be removed.
