### ISSUE TITLE
Старият zip архив от http://www.geocities.com/SiliconValley/Bay/3577/appler.zip

### ISSUE THREAD

**Issue by Twenkid** [zajo/appler#6]
Здравейте, хубаво е че създадохте това хранилище като паметник на чудесната ви разработка с Александър! 
Щях да попитам за оригиналния (стария) архив, който се разпространяваше едно време в Геоситис:
http://www.geocities.com/SiliconValley/Bay/3577/appler.zip

В него имаше документация в текстов файл с тестове и сравнение с други емулатори, с ASCII ART ||||||| 286/12 еди-колко си % от реален Епъл, 386 ||||||  и т.н. Тук не го открих, но докато пишех се сетих да потърся с applersrc.zip и открих. Нямаше го в Архив и oocities, дори във ftp.asimov, но излезе другаде.

https://ftp.sunet.se/mirror/archive/ftp.sunet.se/pub/simtelnet/msdos/emulate/
http://cd.textfiles.com/simtel/simtel0101/simtel/emulate/00_index.htm

И един друг стар документ, списък с емулатори: http://www.faqs.org/faqs/apple2/emulators-faq/part1/ от 1998 г.
```
2.9.3 Appler
-----
HOMEPAGE: http://www.geocities.com/SiliconValley/Bay/3577/appler.html
AVAILABILITY: Available for free download from:
http://www.geocities.com/SiliconValley/Bay/3577/appler.zip
http://www.geocities.com/SiliconValley/Bay/3577/aplersrc.zip (Source Code)

AUTHOR: Emil Dochevsky <[zajo@geocities.com](mailto:zajo@geocities.com)> & Alexander Patalensky.

STATUS: Development in progress. ... ?
(...)
````
* **appler.zip**
  * README.1ST

```
3. SYSTEM REQUIREMENTS
~~~~~~~~~~~~~~~~~~~~~~
Appler needs at least 386 CPU, 1M RAM, 128K EGA, MS DOS 3.30. Emulator
will run faster than an Apple ][ even on slow 386 machine but it is
recommended to use 486/33MHz because on fast computers appler supports
realtime mode. This is useful when you play games or musics -- Apple ][
has no system timers and Apple ][ programs count time by calculating CPU
clocks. See 'APPLER REALTIME MODE' for details.

Appler is DOS software it can run in a DOS window under Windows.
```

```10. PERFORMANCE
~~~~~~~~~~~~~~~
Appler is 100% 80386 assembler code (about 800K source, 22000 lines)
and that's why it is so fast. The following diagram shows the relative
Appler performance in comparison to some other Apple ][ emulators. The
following emulartors are tested:

Appler          - by Alexander Patalenski & Emil Dotchevski
Apl             - by Todor Todorov
Apple           - by Randy Spurlock
][ in a PC      - by Randy Ubillos & David Dixon
CRoss Debugger  - by Nickolay Nickolov

------------------------------------------------------------------------
Appler:         *************************************************** 100%
Apl:            ********************************************* 87%
Apple:          ****************************** 58%
][ in a PC:     **************************** 55%
CRoss Debugger: ******************** 39%
------------------------------------------------------------------------

This test contains intensive video memory usage without page swapping.
When a program often use both pages some of the emulators slows down in
a great degree and this proves Appler performance once more.

The next diagram shows Appler performance on different computers in
comparison to a real Apple ][ (when realtime mode is OFF):

------------------------------------------------------------------------
Apple ][:   ******* 100%
386 SX 20:  ************** 140%
486 SX 20:  *********************** 197%
486 SX 40:  ******************************************************* 400%
------------------------------------------------------------------------

The test does not use the graphics modes e.g. it shows the approximate
computing proformance of the emulated 65C02 processor. For programs that
often address the video memory the real speed is 18-20% less.
```

Пише "386" и се замислих дали не сте го подобрявали впоследствие? Но в изходния код си е 16-bit TASM и т.н.

Поздрави!
[README.1ST[1].TXT](https://github.com/zajo/appler/files/15029859/README.1ST.1.TXT)

**Comment by zajo** [comment]
Както си разбрал, оригиналния архив го има на разни места по нета. Бях забравил за този текстов файл. Не съм сигурен доколко е полезен в днешно време.

Подобрения няма, единствената промяна, която направих напоследък, е да се заобиколи един проблем с DOSBOX, едната от функциите явно не я емулират перфектно и имаше проблеми със събирането на файлове по директориите.

**Comment by Twenkid** [comment]
За полезен - не знам, но интересен - да. Като капсула на времето за "рийдмитата" от едно време. 
Също, за пълнота: открих, че съм качил грешния файл, другото рийдми при изпълнимия файл е с тестовете. [README.1ST.TXT](https://github.com/zajo/appler/files/15045810/README.1ST.TXT)

Исках да използвам случая да ви попитам и дали бихте разказали и други истории от тогава (и след това)? Като интервю/диалог/чат, може да е ако щете в коментари в гитхъб. Или на живо някой ден.  Вие, Алекс, Иво Белчев, Христо Божинов и колегите му от "Висящият замък" ми бяхте "идоли" като български хакери. Навярно има и други (като колегата на Иво в "Космически боец", не го запомних), но вие бяхте достатъчно известни.

През 2010 г. години взех интервю от Алекс в Пловдив, може да ви го е споделял? и да сте чели статията - "Българските хакери". Продължи 4 часа, малко излезе в списанието, някои неща можеше да са скандални и за това също ги бяха махнали. Имаше звукозапис, но с много лошо качество от мп3 плеър, ако го намеря със "здрави битове" и имам време, ще извадя от него съдържание и може първо да ги пратя и на вас, а и на него (надявам се, че е добре след онази тъжна случка), за да добавите нещо, допълните и т.н.

Ако не греша, Алекс спомена за ваше подобрение към прогрите за управление на Робко-01? Спомена някои неща за сътрудничеството Ви с Иво Белчев по Boom-3D, накратко за подсказка, която бил дал за предварителното изчисляване на множество гледни точки, ако не греша, по-голям брой отколкото на Doom, по-бърза работа? За Boom-3D узнах може би дори малко преди да открия Appler, от сайт за 3D-енджини,  може би този:  

https://web.archive.org/web/20130923034903/http://www.3dengines.de/
https://web.archive.org/web/20090712224222fw_/http://www.3dengines.de/feat_all.html  

Ако си идвате в България и Пловдив, бих Ви поканил, както и Алекс, в компютърния музей Compu. Не съм домакинът там, но за такива гости вероятно би се организирало страхотно събитие.

https://www.facebook.com/CompuPlovdiv/?locale=bg_BG

Поздрави!


09.01.1998 [BOOM 3D](https://web.archive.org/web/20090712224222/http://www.geocities.com/SiliconValley/Bay/3577/boom.html)	21.07.1997
B3D is a 3D engine for PCs from Emil Dochevsky ( zajo@geocities.com ) and Ivailo Belchev ( ivob@geocities.com ).
Non orthogonal walls.
Floor and ceiling texture mapping.
Looking up and down.
BOOM can render any geometry that consists of vertical walls and horizontal floors - not only rooms above rooms.
2D sprites.
No lighting, shading or depthcueing yet.
SVGA support.
C++ / ASM source.
More information, screenshots, the demo and source can be found on the [BOOM 3D Engine Homepage](https://web.archive.org/web/20090712224222/http://www.geocities.com/SiliconValley/Bay/3577/boom.html).
